import './jquery.min.js';
import './processing.min.js';
import './all.min.js';
import './TweenMax.min.js';
import './TimelineMax.min.js';
import './ScrollMagic.js';
import './animation.gsap.min.js';
import './smooth-scroll.polyfills.min.js';
import './css-scroll-snap-polyfill@0.1.2.js';